### PR TITLE
Test case for method calls inside classes

### PR DESCRIPTION
**Pull request by camertron**
Test case showing that methods calls inside classes don't get visited.

### CODE REVIEW

**Comment by ioquatix** [comment]
I would like to merge this do you think you could rebase? ha, it's only 2 years later...

**Comment by camertron** [comment]
@ioquatix ok, just rebased and (force) pushed. Are you sure you want to merge this? The test still fails.

**Comment by ioquatix** [comment]
@camertron Thanks so much, yeah I want to test this out on the latest clang and make a minor release to try and get this gem moving again. It's useful and I've one a bunch of work on it.

**Comment by ioquatix** [comment]
@camertron Okay so I found at least the initial problem with the PR. It's because you can't freely parse `void Factory::create()` without knowing what Factory is, apparently. Clang translation unit has diagnostics as such. I've updated the test and changed `class.cpp` so it passes. I'm not sure if this is what you want though? You want to be able to parse a partially complete chunk of C++?

**Comment by camertron** [comment]
@ioquatix huh ok. Maybe it's just that my knowledge of C++ is lacking... but why is the class I included in the PR partially complete? Is it because there's no header file?

**Comment by ioquatix** [comment]
You can see the changes I made, to make that spec pass. https://github.com/ioquatix/ffi-clang/blob/master/spec/ffi/clang/fixtures/class.cpp

**Comment by camertron** [comment]
Ah ok, I get it. Thanks!

**Comment by ioquatix** [comment]
I think the main thing is, it _should_ be possible to parse a partial "thing" but in some cases it may simply be impossible... I'm not sure exactly where that sits with LLVM and exactly what is possible. Perhaps there is a flag, "Parse this thing as much as possible, guess what it should be if it's not clear".

**Pull request merged**
