### PR TITLE
Add support for parse_translation_unit2 api.

### PR DESCRIPTION
**Pull request by cfis**

### CODE REVIEW

**Comment by ioquatix** [comment]
Would it make sense to add a comment explaining why it exists, what problem it solves over the non-2 version?

**Comment by cfis** [comment]
`clang_parseTranslationUnit2` returns an error code indicating what went wrong. In addition, if you look at Clang's documentation, it focuses on clang_parseTranslationUnit2` - see https://clang.llvm.org/doxygen/group__CINDEX__TRANSLATION__UNIT.html#ga494de0e725c5ae40cbdea5fa6081027d.

The docs for `clang_parseTranslationUnit`  are limited, only saying "Same as clang_parseTranslationUnit2, but returns the CXTranslationUnit instead of an error code. In case of an error this routine returns a NULL CXTranslationUnit, without further detailed error codes." See https://clang.llvm.org/doxygen/group__CINDEX__TRANSLATION__UNIT.html#ga2baf83f8c3299788234c8bce55e4472e

Thus my conclusion is use `clang_parseTranslationUnit2` in favor of `clang_parseTranslationUnit`.

**Comment by ioquatix** [comment]
Is there any point to continue providing the original API?

**Comment by cfis** [comment]
No, but I didn't want to be removing existing methods. I'll leave the decision to you.

**Comment by cfis** [comment]
I updated the PR to have `parse_translation_unit` be a alias to `parse_translation_unit2`. I did leave in the FFI definition though.

**Comment by ioquatix** [comment]
What do you think about dropping the alias and `2` suffix? I don’t think this will be a big compatibility issue.

**Comment by cfis** [comment]
That's a good idea. Done.

**Review by ioquatix — APPROVED** [review]

**Pull request merged**
