### PR TITLE
Cursor Improvements, Type improvements, Printing Support

### PR DESCRIPTION
**Pull request by cfis**
This is a grab bag of commits I have been making. New functionality includes adding printing support and methods to tell if a cursor is a opaque (definition in another translation unit) or forward declaration (definition later in translation unit).  The declaration methods are very helpful when auto generating FFI bindings.

If you prefer these commits get separated into different MR's let me know.

### CODE REVIEW

**Comment by ioquatix** [comment]
BTW, for tests, I'm fine with dropping EOL rubies and EOL clangs. Honestly, if it works with the more recent releases, it's good enough.

**Comment by cfis** [comment]
A - weird - two of the failures are the tests that I added which of course did pass locally for me. Will have to see why they didn't on github runner. The other failure I missed, will take a look.

Agree on dropping EOL Ruby/clang versions.

**Comment by cfis** [comment]
Ah I see - I forgot to check in a c header file I added for tests. So now tests pass again. In addition, I upgraded a couple github actions, dropped Ruby 2.7 and 3.0 and added Ruby 3.3

I also tried adding Clang 16/17/18. Clang 16 results in 1 failure (https://github.com/ioquatix/ffi-clang/actions/runs/8517036714/job/23326973558). Clang 17 results in 20 failures (https://github.com/ioquatix/ffi-clang/actions/runs/8517036714/job/23326973994). And Clang 18 is not yet supported by the llvm action.

So I reverted back to Clang 15 since I think those failures are out of scope of this already too large MR and should be dealt with separately. I am happy to look at them once we get this MR wrapped up.

**Review by ioquatix — APPROVED** [review]

**Comment by ioquatix** [comment]
Thanks, this is awesome work.

**Pull request merged**
